#!/bin/bash

# Exit on error
set -e

# Command-line arguments
REBOOT_TARGET="${1}"

#Options and variables
SCRIPT_DIR="$(dirname $(readlink -f "${0}"))"
SCRIPT_PATH="${SCRIPT_DIR}/$(basename "${0}")"
SCRIPT_NAME="$(basename "${0}")"

PARENT_DIR=$(dirname "${SCRIPT_DIR}")
CURRENT_DIR=$(pwd)

GRUB_CFG=/boot/grub/grub.cfg
GRUB_REBOOT=/usr/sbin/grub-reboot

# Functions
check_cmd() {
    if ! type "$1" 1>/dev/null 2>/dev/null
    then
       echo "Error: Command '$1' not found - please install '$1' and try again"
       exit 1
    fi
}

# Check required commands
check_cmd sudo
check_cmd grep
check_cmd "${GRUB_REBOOT}"
check_cmd "boot-remount"

# Get OS names
IFS=$'\n' names=($(grep -oP "^menuentry '\K[^']+" "${GRUB_CFG}"))

echo "Available grub reboot options:"
i=0
for n in "${names[@]}"
do
    echo -e "\t${i}: '${n}'"
    i=$((${i}+1))
done

# Check cmdline param REBOOT_TARGET
target_set=0

if [ "${REBOOT_TARGET}" != "" ]; then
    regex='^[0-9]+$'

    if ! [[ "${REBOOT_TARGET}" =~ $regex ]]; then
        echo "Target must be a zero-positive number, provided: '${REBOOT_TARGET}'"
        exit 1
    fi

    if [ "${REBOOT_TARGET}" -lt 0 ] || [ "${REBOOT_TARGET}" -ge ${#names[@]} ]; then
        echo "Wrong target number provided: '${REBOOT_TARGET}', please select target from [0 to $((${#names[@]} - 1))]"
        exit 1
    fi

    target_set=1
fi

# Select menu options by id
if [ "${target_set}" -eq 0 ]; then
    sel=-1

    while [ ${sel} -lt 0 ] || [ ${sel} -ge ${#names[@]} ]
    do
        read -p "Please select one of the above options [Ctrl+C to exit]:" sel
    done

    REBOOT_TARGET="${sel}"
fi

echo -e "Reboot option selected: \n\t'${names[${REBOOT_TARGET}]}'"

# Request super-user rights
if [ "$(id -u)" -ne 0 ]; then
	echo "Requesting super-user rigths..."
	sudo echo "Rights granted"
fi

# Remount /boot mount point 'rw'
sudo boot-remount "rw"

# Call grub-reboot
echo "Calling '${GRUB_REBOOT} ${REBOOT_TARGET}'"
sudo "${GRUB_REBOOT}" "${REBOOT_TARGET}"

echo "Next reboot switched to '${names[${REBOOT_TARGET}]}'"

exit 0
